name: Transfer newest tweets to Telegram

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch OR schedule cron
on:
  schedule:
  - cron: '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run transfer script
        env:
          TWITTER_CHANNEL_NAME: ${{ secrets.TWITTER_CHANNEL_NAME }}
          TWITTER_BEARER: ${{ secrets.TWITTER_BEARER }}
          TELEGRAM_BOT_NAME: ${{ secrets.TELEGRAM_BOT_NAME }}
          TELEGRAM_CHANNEL_NAME: ${{ secrets.TELEGRAM_CHANNEL_NAME }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python3 twitter2telegram.py
